[package]
name = "running-rs"
version = "0.1.0"
authors = "shivanandvp <shivanandvp@rebornos.org>"
edition = "2018"
description = "A library for running tasks (functions/closures or operating system commands)."
license = "MPL-2.0"
keywords = ["commands", "command", "batch", "jobs", "tasks"] 

[dependencies]

[badges]
maintenance = { status = "experimental" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

